### ISSUE TITLE
多版本是怎么配置的？

### ISSUE THREAD

**Issue by CaoJingBiao** [HGthecode/thinkphp-apidoc#1]
多版本是怎么配置的？

**Comment by HGthecode** [comment]
可以在配置文件 /config/apidoc.php，配置 versions 参数，如下

// 设置可选版本
'versions'=>[
      ['title'=>'V1.0','folder'=>'v1']，
      ['title'=>'V2.0','folder'=>'v2']
],

项目目录结构为如下
app
   |— v1
       |— controller
       ...
   |— v2
       |— controller
       ...
这样将会根据所选的版本读取对应目录下，所配置的controllers 的接口

**Comment by CaoJingBiao** [comment]
额，这就麻烦了，我的目录结构是app->api->controller->v1/v2

**Comment by CaoJingBiao** [comment]
解决了，配置文件改成
//生成文档的控制器
    'controllers' => [
        'GetAppToken',
    ],
    // 设置可选版本
    'versions'=>[
        ['title'=>'V1.0','folder'=>'api\\controller\\v1'],
        ['title'=>'V2.0','folder'=>'api\\controller\\v2']
    ],
这样也行，哈哈

**Comment by HGthecode** [comment]
赞！这样也可以的，版本目录只是会在生成文档的控制器前面加上版本地址，只要地址对了，就OK的

**Comment by CaoJingBiao** [comment]
找了好几个支持TP6的文档生成扩展，大多数都有BUG，还是你这个最好用，方便，赞！感谢！
