### ISSUE TITLE
找了很久没找到联系方式

### ISSUE THREAD

**Issue by tlerbao** [HGthecode/thinkphp-apidoc#10]
阅读了您写的，使用Github Actions 实现TP6自动化部署，收益匪浅，准备把项目的部署方式改为 actions。

但是运行到 
![image](https://user-images.githubusercontent.com/20442232/110597329-60554300-81bb-11eb-95e4-6af6c43c1dde.png)

这里报错了，请问具体原因是什么导致的呢？

**Comment by HGthecode** [comment]
可以通过QQ：376401263 联系我，欢迎一起交流😃
