### ISSUE TITLE
插件安装问题

### ISSUE THREAD

**Issue by MrYZhou** [HGthecode/thinkphp-apidoc#11]
composer require hg/apidoc 执行后，没有生成config.php,导致http://www.mytt.com/apidoc/config 404
![3AERV42~IUDBGWDIEE`9WSR](https://user-images.githubusercontent.com/44339602/112414255-b9e17400-8d5c-11eb-8453-3ac52a953141.png)

![MW`X NXGLBTVJL5{AUNFFQO](https://user-images.githubusercontent.com/44339602/112414165-8ef72000-8d5c-11eb-8fa3-2bcb8d347c30.png)

**Comment by MrYZhou** [comment]
![Uploading image.png…]()
我这个apidoc2.4.1 下前端是2.4.0没问题吧

**Comment by HGthecode** [comment]
如果你的tp6.x版本的话apidoc/config接口报404并不是缺少config文件，而是插件自动注册的路由没有生效。
可能是站点目录配置不对或伪静态配置不对(可通过用tp写的api接口，看是否访问正常的，来排除此类原因)，你也可以尝试像这样。
如果你的项目有其它特别之处，也可加Q：376401263(务必备注apidoc)联系我帮你分析具体原因。

**Comment by HGthecode** [comment]
该问题在 [文档-常见问题-404错误](https://hgthecode.github.io/thinkphp-apidoc/use/help/#_404%E9%94%99%E8%AF%AF)中 做了详细的描述
