### ISSUE TITLE
这个路径有问题多了个apidoc

### ISSUE THREAD

**Issue by raymondZhong** [HGthecode/thinkphp-apidoc#12]
执行提交的时候，这个路径有问题多了个apidoc
http://tp2021:8888/apidoc/admin_api/Login/index 错误
应该是
http://tp2021:8888/admin_api/Login/index

错误URL
http://tp2021:8888/apidoc/admin_api/Login/index?username=teset&password=123456&phone=111111&sex=1

**Comment by HGthecode** [comment]
如果是在使用接口调试时，请求路径加上了当前页面的路径的问题，请检查定义api接口的url要以/开头。

**Comment by HGthecode** [comment]
已在v2.4.2版本中做了自动补全处理，杜绝了url以/开头的漏写问题
