### ISSUE TITLE
格式规范

### ISSUE THREAD

**Issue by xiaoxiaoxiaox** [HGthecode/thinkphp-apidoc#14]
## 深层对象的格式不规范

![image](https://user-images.githubusercontent.com/37464637/113257735-9b035480-92fd-11eb-8866-edb37ed25f90.png)

**Comment by HGthecode** [comment]
[v2.4.2版本](https://hgthecode.github.io/thinkphp-apidoc/guide/changelog/#v2-4-2)中已修复该问题
