### ISSUE TITLE
期望可以增加控制器名称显示/关闭的开关

### ISSUE THREAD

**Issue by xiaoxiaoxiaox** [HGthecode/thinkphp-apidoc#15]
### **如下图,我不想让别人看到我的控制器名称**

![image](https://user-images.githubusercontent.com/37464637/113370191-cd609080-9395-11eb-9682-0cc66cede99c.png)
![image](https://user-images.githubusercontent.com/37464637/113370208-d81b2580-9395-11eb-9e62-55d79dd7080d.png)

**Comment by HGthecode** [comment]
计划将在下个版本，通过配置来控制此类显示

**Comment by HGthecode** [comment]
你好！在v2.5.0版本支持通过以下前端配置文件来配置实现,如下：
public/apidoc/config.js

```javascript
var config = {
  // 请求host
  HOST: "",
  // 菜单配置
  MENU: {
    // 是否显示控制器类名
    SHOW_CONTROLLER_CLASS: true,
    // 是否显示接口url
    SHOW_API_URL: true,
    // 是否显示接口请求类型
    SHOW_API_METHOD: true
  }
};
```
