### ISSUE TITLE
怎么没token方式效验

### ISSUE THREAD

**Issue by dbb987** [HGthecode/thinkphp-apidoc#16]
看见访问api目前只是密码效验，这个固定的密码不安全吧，抓包一下获取就完了，应该用token效验，

**Comment by HGthecode** [comment]
文档的访问验证并非固定密码传递来验证，是通过输入密码验证后生成token（非JWT生成的token，主要考虑到减少依赖）之后的apidoc/data接口都会携带这个token来做校验，具体可看下源码。但确实的是，目前版本对这个token生成规则比较简单，下个版本会调整其生成规则。如果有什么好的建议或实现方式也可反馈给我哈

**Comment by dbb987** [comment]
嗯，那就好，那我就用用看，你用过phalApi的api框架嘛，可以加你微信吗，我的dan520_baby
