### ISSUE TITLE
tp5使用v1版本没有生config/apidoc.php文件

### ISSUE THREAD

**Issue by Risin9** [HGthecode/thinkphp-apidoc#17]
tp5使用v1版本没有生config/apidoc.php文件，另外，下载前端页面链接失效.
![image](https://user-images.githubusercontent.com/28332139/116099824-f0553a80-a6de-11eb-9498-2d7b28e2e628.png)
![image](https://user-images.githubusercontent.com/28332139/116099929-09f68200-a6df-11eb-9d89-6a84dafe92eb.png)

**Comment by HGthecode** [comment]
1、使用了composer2版本安装可能会导致不生成config/apidoc.php配置文件，可降级composer版本再安装，或将插件目录下`vendor/hg/apidoc/config.php`文件拷贝到`config/`目录下使用。
2、v1版本的下载地址已更新，可下载[v1.0.0](https://github.com/HGthecode/apidoc-ui/releases/download/v1.0.0/apidoc.zip)
