### ISSUE TITLE
如何在基类或者控制器统一加上@Apidoc\Header("Authorization", require=true, desc="Token") 

### ISSUE THREAD

**Issue by qq951692996** [HGthecode/thinkphp-apidoc#19]
比如说，我的控制器有很多方法，有什么办法可以不用每个方法都加上
@Apidoc\Header("Authorization", require=true, desc="Token")

**Comment by HGthecode** [comment]
你好，可通过config/apidoc.php的[配置参数headers](https://hg-code.gitee.io/thinkphp-apidoc/config/#headers)，实现所有接口的请求头公共参数，如某些接口不需要全局的参数，可在接口注解处加上[特殊参数NotHeaders](https://hg-code.gitee.io/thinkphp-apidoc/use/#%E7%89%B9%E6%AE%8A%E5%8F%82%E6%95%B0)来让指定接口不自动加上全局参数。
