### ISSUE TITLE
多级控制器bug修复代码

### ISSUE THREAD

**Issue by longa30** [HGthecode/thinkphp-apidoc#20]
protected function autoCreateUrl($method): string
    {
        $isAuto = Config::get('controller_auto_search')||in_array('controller_auto_search',$this->config);
        $pathArr = [];
        if ($isAuto){
            $pathArr = explode("\\", $method->class );
        }else{
            $searchString = $this->controller_layer . '\\';
            $substr = substr(strstr($method->class, $searchString), strlen($searchString));
            $pathArr = explode("\\", str_replace($substr, str_replace('\\', '.', $substr), $method->class));
        }
        // 控制器地址
        $filterPathNames = array("app", $this->controller_layer);
        $classPathArr = [];
        foreach ($pathArr as $item) {
            if (!in_array($item, $filterPathNames)) {
                $classPathArr[] = $item;
            }
        }

        $classPath = implode('/', $classPathArr);

        return '/' . strtolower($classPath) . '/' . $method->name;
    }

**Comment by HGthecode** [comment]
感谢你参与到apidoc的建设中来，让apidoc越来越完善。由于`controller_auto_search`配置在tp6中已废弃，所以$isAuto的判断是否有点多余?直接如下

**Comment by longa30** [comment]
之所以用 Config::get('controller_auto_search') 是因为该插件面对大众的。。。希望以框架内置的属性优先。更好的适用tp5.这是我写在前面的原因。

**Comment by HGthecode** [comment]
这样的考虑非常好，原来2.0版本因为一些原因没有对tp5的支持，这段时间也有很多用户反映希望支持tp5。
我已经做好了对tp5的兼容处理，现在在大量测试和写示例，下个版本发布就会兼容tp5了。
你的这个多级控制器修正建议也已采纳，再次感谢
