### ISSUE TITLE
自定义目录生成控制器 配置无效

### ISSUE THREAD

**Issue by aron0524** [HGthecode/thinkphp-apidoc#21]
![image](https://user-images.githubusercontent.com/10445866/125219884-49a13300-e2f8-11eb-953b-09b88f15af66.png)

**Comment by HGthecode** [comment]
你好，我通过与你相同的目录及controllers配置测试能正常解析，可以提供更详细的复现代码，以便分析具体原因。
额外：一般不建议配置controllers，由插件通过配置的apps自动生成看能不能正常解析出来
