### ISSUE TITLE
Url自动生成优化建议

### ISSUE THREAD

**Issue by tuyazuo** [HGthecode/thinkphp-apidoc#22]
多应用模式下自动生成的url总是会附带app字符，导致访问地址不正确，建议增加个配置，可以去掉自动附带app。
例如  host/nm/comm/index.php 自动生成的url为  host/app/nm/comm/index.php
在实际开发中，基本上url都是不需要重新定义的，期望自动生成时也能正确。

**Comment by tjztj** [comment]
我的解决方法是在index模块下面的路由加入下面这个路由，替换掉原来的路由

    //替换掉自动生成的url
    Route::group('apidoc',function () {
        Route::get('apiData', '\hg\apidoc\Controller@getApidoc')->middleware(function(Request $request, \Closure $next){
            $response=$next($request);
            $data=$response->getData();
            if(!isset($data['code'], $data['data']['list'])){
                return $response;
            }
            foreach ($data['data']['list'] as $k=>$v){
                if(empty($v['children'])){
                    continue;
                }
               foreach ($data['data']['list'][$k]['children'] as &$actionInfo){
                   if(empty($actionInfo['url'])||stripos($actionInfo['url'],'/app/')!==0){
                       continue;
                   }
                   $actionInfo['url']=substr($actionInfo['url'],4);
                }
            }
            $response->data($data);
            return $response;
        });
    });

**Comment by HGthecode** [comment]
在自动生成url的方法中存在过滤掉 app、controller 来生成url的规则，可以看看你的项目中 `App::getNamespace()` 输出的是什么。
![issues22](https://apidoc.demo.hg-code.com/images/lssue/issues22.png)

**Comment by tjztj** [comment]
> 在自动生成url的方法中存在过滤掉 app、controller 来生成url的规则，可以看看你的项目中 `App::getNamespace()` 输出的是什么。
> ![问题22](https://camo.githubusercontent.com/34fb40963af05255a2931c62fd5142be925442109894f47a82b4f12412691b31/68747470733a2f2f617069646f632e64656d6f2e68672d636f64652e636f6d2f696d616765732f6c737375652f69737375657332322e706e67)

打印出来是 'app/index'

**Comment by HGthecode** [comment]
你应该是在index应用的接口中打印App::getNamespace() 吧！而apidoc扩展不属于某个应用，所以在autoCreateUrl方法中`App::getNamespace()`输出的应该是app；你可以尝试修改apidoc的autoCreateUrl方法的源码看看输出：
![issues22-1](https://apidoc.demo.hg-code.com/images/lssue/issues22-1.png)

**Comment by tjztj** [comment]
> 你应该是在index应用的接口中打印App::getNamespace() 吧！而apidoc扩展不属于某个应用，所以在autoCreateUrl方法中`App::getNamespace()`输出的应该是app；你可以尝试修改apidoc的autoCreateUrl方法的源码看看输出：
> ![issues22-1](https://camo.githubusercontent.com/bdc2842012fbc4328f55373a4975912fd82763dc5c92357da667b9d893c8050a/68747470733a2f2f617069646f632e64656d6f2e68672d636f64652e636f6d2f696d616765732f6c737375652f69737375657332322d312e706e67)

就是‘app/index’

可能是跟TP的默认模块有关，只要没有找到模块，统统走index
![image](https://user-images.githubusercontent.com/17394651/127596770-4af1b271-2c0f-45b5-a2d7-0b41b02eb00a.png)

这是url：`http://127.0.0.1:8000/apidoc/apiData?appKey=`

**Comment by HGthecode** [comment]
我尝试了配置 `app_namespace` 及`default_app`之类的配置，还是无法复现问题，如果方便的话，可以发一份复现的程序给我，来了解问题的原因或从apidoc寻求如何优化。

**Comment by tjztj** [comment]
> 我尝试了配置 `app_namespace` 及`default_app`之类的配置，还是无法复现问题，如果方便的话，可以发一份复现的程序给我，来了解问题的原因或从apidoc寻求如何优化。

![image](https://user-images.githubusercontent.com/17394651/127597829-d4c80c23-4f76-4a1d-a675-e3307e6d45f7.png)
![image](https://user-images.githubusercontent.com/17394651/127597866-e0d4e6d0-5d49-416d-aa26-63131e4ede7a.png)
![image](https://user-images.githubusercontent.com/17394651/127597923-e7278d0d-d747-4bd7-91f7-737f2243b8d2.png)

TP的源码中可以看到，如果我没有配置‘app_namespace’，`'app\\' . $appName`这种格式

**Comment by HGthecode** [comment]
我再在tp6中测试，apidoc前端会通过/apidoc/apiData?appKey=xxx 接口获取指定应用的api文档，该路由为apidoc扩展自动注册其并不属于某个应用。访问该接口时，并不会进入 think-multi-app扩展的`setApp`方法，所以在该接口实现中通过`App::getNamespace()`获取到的是，$namespace最初始定义的值。

![issues22-2](https://apidoc.demo.hg-code.com/images/lssue/issues22-2.png)

在下个版本（3.0）中，增加了配置`autoCreateUrl`自定义对自动生成url的函数。

**Comment by wgsuxin** [comment]
如果App::getNamespace()返回为 app/xxx 的形式，应该是app.php配置文件里设置了 'app_express'=>true 的原因，改成false或直接去掉返回就是'app'了
