### ISSUE TITLE
切换分组时会报404错误，应该切换时关闭tab保证不加载不存在页面

### ISSUE THREAD

**Issue by ZHT131** [HGthecode/thinkphp-apidoc#23]
![image](https://user-images.githubusercontent.com/22323594/131439632-f53969e3-9ce3-43d1-8fb2-7126c3da334d.png)
如图所示

**Comment by HGthecode** [comment]
你好，此bug已解决，请下载最新前端文件覆盖即可[UI 2.0.1](https://hg-code.gitee.io/thinkphp-apidoc/guide/install/#%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2)

**Comment by ZHT131** [comment]
> 你好，此bug已解决，请下载最新前端文件覆盖即可[UI 2.0.1](https://hg-code.gitee.io/thinkphp-apidoc/guide/install/#%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2)

好的，我试试

**Comment by ZHT131** [comment]
> 你好，此bug已解决，请下载最新前端文件覆盖即可[UI 2.0.1](https://hg-code.gitee.io/thinkphp-apidoc/guide/install/#%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2)

目前的处理是保留之前打开的某应用分组下接口的tab吗？我还以为是切换应用后直接清除掉所有tab回到首页呢

**Comment by HGthecode** [comment]
是的，保留原来已打开的，因为有需要多应用之间的接口联调的场景
