### ISSUE TITLE
多应用多版本应用名称为下划线 会存在问题。

### ISSUE THREAD

**Issue by aron0524** [HGthecode/thinkphp-apidoc#25]
如题，ooxx_aaa_vvv
`
        [
            'title'=>'xxxxx子系统',
            'folder'=>'ooxx_aaa_vvv',
            'items'=>[
                ['title'=>'V1.0','path'=>'app\ooxx_aaa_vvv\controller\v1','folder'=>'v1'],
                ['title'=>'V2.0','path'=>'app\ooxx_aaa_vvv\controller\v2','folder'=>'v2']
            ]
        ],
`
版本切换时会有问题 读不到配置

**Comment by HGthecode** [comment]
你好，该问题已解决，请升级最新版本即可

**Comment by aron0524** [comment]
现在又有新的问题出现了。前端ui界面 多应用多版本模式下 ，点击左上角切换版本，第一次没问题。多上下滑动下选择版本会出现重复版本问题。

**Comment by HGthecode** [comment]
请问下具体能复现的操作时如何的呢？是比较多的应用/版本下拉框里面的滚动条上下滑动时会出现问题吗？请详细描述一下问题的复现操作，我能复现问题才好解决哦

**Comment by aron0524** [comment]
对的。就是很多应用的时候，版本切换滚动条 上下多滑动几次 就会出现 应用版本错乱问题。

**Comment by aron0524** [comment]
对的。就是很多应用的时候，版本切换滚动条 上下多滑动几次 就会出现 应用版本错乱问题。

**Comment by HGthecode** [comment]
你好，该问题在v3.0.2已修正
