### ISSUE TITLE
复制文档的代码也生成不了文档，改配置文件却有用

### ISSUE THREAD

**Issue by 15673470531** [HGthecode/thinkphp-apidoc#26]

**Comment by HGthecode** [comment]
你好，请详细描述一下问题哦

**Comment by 15673470531** [comment]
我只想知道为什么我写了接口，但是文档刷新却没有

**Comment by 15673470531** [comment]
复制你的注释体验也无效

**Comment by HGthecode** [comment]
没有正常显示注解的接口，可通过以下几个情况配合演示代码排查：

## 当前应用所有有注解的 控制器/接口都没有显示？

检查配置apps当前应用的path是否配置正确


## 有些控制器中及接口有显示，新增的控制器及接口不显示？

1、检查当前应用是否配置了`controllers` 如果配置了，加上新增的控制器

2、检查是否存在`NotParse`的注释


## 控制器显示，里面的接口不显示

1、检查接口是否存在注解（存在注解的才会被解析）

2、检查是否存在`NotParse`的注释

如果还是不能正常显示，可加我q：376401263 了解你的具体情况，帮你解决问题
