### ISSUE TITLE
是否支持restful格式接口呢

### ISSUE THREAD

**Issue by YaoShuwei** [HGthecode/thinkphp-apidoc#28]
翻了几遍文档，没看到如何支持restful格式的接口，@Apidoc\Param只能用query来接收

**Comment by YaoShuwei** [comment]
又仔细看了一遍，配置ParamType即可，打扰了。

**Comment by YaoShuwei** [comment]
我有个接口，PUT: '/product/:id'  data: {'name':'mock'} ，请问应该如何定义

**Comment by HGthecode** [comment]
你好，你可以尝试这样的注解：
```php
/**
     * @Apidoc\Title ("路由带参")
     * @Apidoc\Url("/product/:id")
     * @Apidoc\Method("PUT")
     * @Apidoc\Param("name",type="string",desc="姓名")
     * @Apidoc\ParamType("route")
     */
```

**Comment by YaoShuwei** [comment]
> 你好，你可以尝试这样的注解：
> 
> ```
> /**
>      * @Apidoc\Title ("路由带参")
>      * @Apidoc\Url("/product/:id")
>      * @Apidoc\Method("PUT")
>      * @Apidoc\Param("name",type="string",desc="姓名")
>      * @Apidoc\ParamType("route")
>      */
> ```

感谢作者这么快进行回复，我测试了一下，发现以下问题，不知应该如何解决

![image](https://user-images.githubusercontent.com/17966298/134809734-31c4e63e-05ed-4a38-ab97-8755a9f5c40f.png)
![image](https://user-images.githubusercontent.com/17966298/134809788-ee4e2bef-f74b-4c5e-88e3-72e3ef0c4cf1.png)

**添加参数id后，无法接收name**


![image](https://user-images.githubusercontent.com/17966298/134809856-83233825-3fe1-4568-9ced-4eb1ec1f2caf.png)
![image](https://user-images.githubusercontent.com/17966298/134809867-740c60d1-c081-4187-aecb-b9e0e9ce5099.png)

**Comment by YaoShuwei** [comment]
使用postman可以正常访问
![image](https://user-images.githubusercontent.com/17966298/134809996-3d30804e-cfe2-49a0-8f0f-e3dad869ebce.png)

**Comment by HGthecode** [comment]
这是个bug，问题在于将参数转成路由参数时将非路由定义的参数给丢掉了，我已经在修复这个bug了，晚点更新后就能解决了

**Comment by YaoShuwei** [comment]
静候佳音

**Comment by HGthecode** [comment]
你好，已经更新了，本次只更新了前端文件，所以无需升级apidoc，直接[下载前端文件](https://hg-code.gitee.io/thinkphp-apidoc/guide/install/#%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2)覆盖即可。

**Comment by YaoShuwei** [comment]
牛批PLUS，已测试OK，感谢
![image](https://user-images.githubusercontent.com/17966298/134812490-4f314afe-f38e-4294-8937-1e29ca7123ee.png)
