### ISSUE TITLE
global_auth_key 

### ISSUE THREAD

**Issue by nimageji8** [HGthecode/thinkphp-apidoc#3]

**Comment by nimageji8** [comment]
global_auth_key 配置没有生效

**Comment by HGthecode** [comment]
感谢反馈，已解决。请下载最新的前端文件，覆盖原public/apidoc [添加前端页面](https://hgthecode.github.io/thinkphp-apidoc/install/#%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2)
