### ISSUE TITLE
在调试时,调试路径多了一个目录,如何配置?

### ISSUE THREAD

**Issue by Yvesjava** [HGthecode/thinkphp-apidoc#31]
API接口地址:   /shop/user.User/getChildren
访问时的路径:    host/index.php/shop/shop/user.User/getChildren
正确的地址:     host/index.php/shop/user.User/getChildren

这里多了一个 shop
请问如何配置
apidoc.php中的apps如下配置
`[
            'title'  => 'shop端',
            'path'   => 'app\shop\controller',
            'folder' => 'shop',
            'groups' => [
                ['title' => '基础模块', 'name' => 'base'],
                ['title' => '功能模块', 'name' => 'function'],
            ],
        ]`

前端 config.js
`HOSTS: [
      {
        title: "shop",
        host: "http://test.com"
      },
    ],`

**Comment by HGthecode** [comment]
你好，如果apidoc默认自动生成的接口url不准确的话，可以通过以下两种方式解决：

#### 1、自定义生成方法：
```php
// config/apidoc.php

// 自动生成ur配置
auto_url' => [
       // 自定义生成函数，（供参考，根据你的项目情况调整该方法）
        'custom' =>function($class,$method){
            $class = str_replace('app','',$class);
            $class = str_replace('controller','',$class);
            $class = str_replace('\\','/',$class);
            $class = str_replace('//','/',$class);
            return $class."/".$method;
        },
    ],
```

#### 2、接口注解 `@Apidoc\Url ("xxxxxx")`

**Comment by Yvesjava** [comment]
@HGthecode 
非常感谢快速回复
第二个方法我知道的,试过成功了,但是每个接口都需要这样处理,比较麻烦,期待接下来的更新

第一个方法
我刚刚尝试过了
确实可以把接口的地址改变到自己想要的效果
但没有文档,不利于新手哇

**Comment by HGthecode** [comment]
文档里面有描述哈 [https://hg-code.gitee.io/thinkphp-apidoc/config/#auto-url-custom](https://hg-code.gitee.io/thinkphp-apidoc/config/#auto-url-custom)，至于自定义方法内如何实现，就得根据自身系统情况来写了，就是一些字符串处理的逻辑....没法形成标准的。

**Comment by Yvesjava** [comment]
好的,谢谢了
根据方案一 已经成功了

**Comment by HGthecode** [comment]
好的，欢迎点个Star 😎
