### ISSUE TITLE
配置无API 列表，多级目录

### ISSUE THREAD

**Issue by zhangvoice** [HGthecode/thinkphp-apidoc#32]
文件目录：

<html>
application<br>
&nbsp;&nbsp;&nbsp;&nbsp;maintain<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;home<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;api<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User.php<br>
</html>
				
						
配置文件:config/apidoc.php
apps 配置
'apps' => [
	['title'=>'API 接口','path'=>'app\maintain\home\api','folder'=>'api'],
]

User.php 命名空间：app\maintain\home\api;

User.php 内容:

	/**
     * @Apidoc\Title("基础的注释方法")
     * @Apidoc\Desc("最基础的接口注释写法")
     * @Apidoc\Method("GET")
     * @Apidoc\Author("HG-CODE")
     * @Apidoc\Tag("测试")
     * @Apidoc\Param("username", type="abc",require=true, desc="用户名")
     * @Apidoc\Param("password", type="string",require=true, desc="密码")
     * @Apidoc\Param("phone", type="string",require=true, desc="手机号")
     * @Apidoc\Param("sex", type="int",default="1",desc="性别" )
     * @Apidoc\Returned("id", type="int", desc="用户id")
     */
public function login()
{}

api 请求地址: http:// host /maintain/api.user/login

请问如何配置，目前配置没有API列表

**Comment by HGthecode** [comment]
请问你的项目是什么tp版本？5.0还是5.1？ 

还有，apps配置中的`path`，指该应用的目录，并不是命名空间，所以你的path应该是

```php
['title'=>'API 接口','path'=>'application\maintain\home\api','folder'=>'api'],
```

**Comment by zhangvoice** [comment]
感谢回复

TP5.1 版本
目前 path 已修改为 :application\maintain\home\api
但出现 ParseAnnotation.php 文件 395 行出现 报错：`类型错误: substr() expects parameter 1 to be string, bool given`
原因是默认控制  $this->controller_layer 默认配置是  controller  ,添加 route.php 配置文件并添加 controller_layer 配置解决，再次感谢
