### ISSUE TITLE
  请求参数类型ParamType("formdata")时，全局参数获取不到值

### ISSUE THREAD

**Issue by yujin4733** [HGthecode/thinkphp-apidoc#34]
用After(event="setGlobalParam"）事件设置一个全局参数并赋值,当请求参数类型为formdata时，调试其他接口，全局参数没有值，使用默认请求类型时有值。

**Comment by HGthecode** [comment]
你好，此问题已修正，请升级至[v3.0.7](https://hg-code.gitee.io/thinkphp-apidoc/guide/changelog/#v3-0-7)
