### ISSUE TITLE
Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by khongshao** [HGthecode/thinkphp-apidoc#37]
你好，参照文档[从0创建TP6新项目与Apidoc的安装]步骤，thinkphp为6.0.9版本，这个问题如何处理

**Comment by khongshao** [comment]
thinkphp-apidoc-demo，clone 完后，composer install   + php think run 
访问http://127.0.0.1:8000/apidoc/#/home
依然报这个错误

**Comment by khongshao** [comment]
使用环境为dokcer , php:7.3-cli

**Comment by HGthecode** [comment]
请使用集成环境访问站点，`php think run`启动的不行
