### ISSUE TITLE
当我header值中包含空格时，会自动编码成%20

### ISSUE THREAD

**Issue by lzp91** [HGthecode/thinkphp-apidoc#38]
![image](https://user-images.githubusercontent.com/5674244/147828018-123c0102-8d90-41bd-ba10-04af89e9ea38.png)
![image](https://user-images.githubusercontent.com/5674244/147828036-b674bf11-49e1-4a10-8dd9-e79b04963e2d.png)

**Comment by HGthecode** [comment]
这是因为请求头参数默认使用了encodeURIComponent 转码导致的；升级到3.1.0版本可在apidoc/config.js配置文件中配置 `HTTP.HEADERS_ENCODEURICOMPONENT` 为 `false`来关闭它

```js
// 请求配置
  HTTP: {
    // 请求头 encodeURIComponent 转码
    HEADERS_ENCODEURICOMPONENT: false,
   //.....
  },
```
