### ISSUE TITLE
调试中字段如果为文件类型可以加入上传文件功能吗？

### ISSUE THREAD

**Issue by ZHT131** [HGthecode/thinkphp-apidoc#39]
调试中字段如果为文件类型可以加入上传文件功能来方便调试吗？

**Comment by HGthecode** [comment]
接口注解中的请求参数字段类型为`file`，并且指定参数类型为`formdata`时，字段可上传文件。可以参考演示效果：
[https://apidoc.demo.hg-code.com/apidoc/#/api?key=admin_POST_/admin/baseDemo/upload&appKey=admin](https://apidoc.demo.hg-code.com/apidoc/#/api?key=admin_POST_/admin/baseDemo/upload&appKey=admin)

该演示接口的注解如下：

```php
/**
  * @Apidoc\Title("文件上传")
  * @Apidoc\Url("/admin/baseDemo/upload")
  * @Apidoc\Method("POST")
  * @Apidoc\ParamType("formdata")
  * @Apidoc\Param("file",type="file", require=true,desc="附件")
  * @Apidoc\Returned("url", type="string",desc="文件地址")
  */
  public function upload(){
      //...
  }
```

**Comment by ZHT131** [comment]
原来已经支持了啊，文档之前好像没找到
