### ISSUE TITLE
集成后报错

### ISSUE THREAD

**Issue by 21808505** [HGthecode/thinkphp-apidoc#41]
我用的TP6，入口文件在项目根目录，不在public下。按照文档安装配置apidoc后一直报错：控制器不存在:app\controller\Config
按照常见问题里提供的方法配置之后也还是报这个错。
我分别尝试把前端页面apidoc目录放在项目根目录下、放到public目录下都报上述错误。
该如何处理呢？

**Comment by HGthecode** [comment]
我尝试过，复制public的index.php入口文件到根目录，并修改 `require __DIR__ . '/vendor/autoload.php';` 然后访问 /public/apidoc/ 是正常的。
不清楚你的项目具体问题，可以加我Q：376401263（备注 apidoc）详细了解你的项目情况，帮你分析问题

**Comment by 21808505** [comment]
感谢作者的指导！其实正常集成非常简单，一般都是集成到项目中比较困难，最终通过反复测试发现是我项目对路由做了限制~~~
