### ISSUE TITLE
php >=8.0 but your php version (7.4.26) does not satisfy that requirement.

### ISSUE THREAD

**Issue by chuxinone** [HGthecode/thinkphp-apidoc#42]
建议增加8.0版本支持

**Comment by HGthecode** [comment]
你好，实测是 支持php8.0及php8.1的哈

**Comment by chuxinone** [comment]
你好 使用的是tp6 然后将配置文件php版本为更改8 phpstorm提示不支持8.0&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 7, 2022 11:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HGthecode/thinkphp-apidoc] php &gt;=8.0 but your php version(7.4.26) does not satisfy that requirement. (Issue #42)




 
你好，实测是 支持php8.0及php8.1的哈
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
