### ISSUE TITLE
同控制器下能不能通过接口分组

### ISSUE THREAD

**Issue by aaron-code-life** [HGthecode/thinkphp-apidoc#44]
现在只能根据控制器分组，能不能一个控制器在不分控制器的前提的下对不同api进行分组

**Comment by HGthecode** [comment]
分组功能是将控制器来分组，无法以api接口来分组。可尝试通过给接口添加不同的Tag来区分。

**Comment by aaron-code-life** [comment]
感谢回复，但是Tag不支持搜索过滤，前端在查阅接口文档的时候没法很好的区分

**Comment by HGthecode** [comment]
菜单上方可过滤tag的哈
![](https://apidoc.demo.hg-code.com/images/lssue/tags.jpg)

**Comment by aaron-code-life** [comment]
感谢感谢
