### ISSUE TITLE
开启密码验证访问，报500错误

### ISSUE THREAD

**Issue by yuwenlwl** [HGthecode/thinkphp-apidoc#49]
无密码访问一切正常，只要一开启密码验证，就报500错误，也没个错误提示

**Comment by yuwenlwl** [comment]
在network里显示不存在token

**Comment by HGthecode** [comment]
你好，如果开启了密码访问，apidoc接口会响应401状态码，如果不是401状态码，请检查你项目的全局异常处理，是否处理掉了apidoc抛出的异常状态码。如果响应401则会正常弹出密码输入框

**Comment by HGthecode** [comment]
你好，如果开启了密码访问，apidoc接口会响应401状态码，如果不是401状态码，请检查你项目的全局异常处理，是否处理掉了apidoc抛出的异常状态码。如果响应401则会正常弹出密码输入框

**Comment by Yvesjava** [comment]
`
if ($e instanceof AuthException) {
            return parent::render($request, $e);
        }
`
