### ISSUE TITLE
建议新增Header通用注释

### ISSUE THREAD

**Issue by Z-Sirius** [HGthecode/thinkphp-apidoc#5]

**Comment by HGthecode** [comment]
感谢您的反馈，已经在[v2.0.2](https://hg-code.gitee.io/thinkphp-apidoc/v2/changelog/#v2-0-2) 版本中支持Header 使用ref引用。您可以像使用Param或Returned一样在Header中使用ref

**Comment by Z-Sirius** [comment]
Header不支持type参数，与手册描述不符。

**Comment by Z-Sirius** [comment]
Header不支持type参数，与手册描述不符。

**Comment by HGthecode** [comment]
已修正该bug，请升级最新版
