### ISSUE TITLE
作者可否有计划兼容webman框架呢？

### ISSUE THREAD

**Issue by ZHT131** [HGthecode/thinkphp-apidoc#50]
在thinkphp中使用确实很不错！
作者可否有计划兼容webman框架呢？

**Comment by ZHT131** [comment]
这么好的插件不应该局限于tp，兼容php生态就厉害了

**Comment by HGthecode** [comment]
你好，目前在进行laravel版的开发，由于想尽可能降低指定框架安装及配置的门槛，就针对框架来实现了。等后续如果有时间会考虑不强依赖框架的尝试哈

**Comment by ZHT131** [comment]
好吧

**Comment by HGthecode** [comment]
你好，最新的v4版本已支持webman框架了哈，[https://github.com/HGthecode/apidoc-php](https://github.com/HGthecode/apidoc-php)
