### ISSUE TITLE
控制器开启后缀配置，接口生成请求url错误，带着contrller

### ISSUE THREAD

**Issue by genieba** [HGthecode/thinkphp-apidoc#57]

**Comment by HGthecode** [comment]
自动生成url只是简单将控制器目录和方法名生成，如果无法达到效果，可以参考文档 [https://hg-code.gitee.io/thinkphp-apidoc/config/#auto-url-custom](https://hg-code.gitee.io/thinkphp-apidoc/config/#auto-url-custom) 使用自定义方法来控制生成。
