### ISSUE TITLE
为啥安装了，api页面显示不出API列表

### ISSUE THREAD

**Issue by CaoJingBiao** [HGthecode/thinkphp-apidoc#6]
重新安装了，api页面显示正常，后台配置信息前台也能正常显示和使用，控制器注释按照格式写的，但是api页面就是不显示API列表，左侧空白

**Comment by HGthecode** [comment]
可通过配置需要解析的控制器 [config.controllers](https://hg-code.gitee.io/thinkphp-apidoc/v2/config/#controllers)，如还是不行，可q:376401263，备注apidoc联系我，了解你使用的具体问题，帮你分析

**Comment by ScientistPun** [comment]
已经配置了config.controllers，左右两侧依然空白，network访问的资源显示：We're sorry but apidoc doesn't work properly without JavaScript enabled. Please enable it to continue.

**Comment by HGthecode** [comment]
@ScientistPun 你是通过 `php think run` 来运行站点的吗？请使用集成环境来运行站点。文档教程此处有说明：[TP6新项目的创建与Apidoc的安装- 建议](https://hgthecode.github.io/thinkphp-apidoc/course/createTpAndInstall)

**Comment by ScientistPun** [comment]
> @ScientistPun 你是通过 `php think run` 来运行站点的吗？请使用集成环境来运行站点。文档教程此处有说明：[TP6新项目的创建与Apidoc的安装- 建议](https://hgthecode.github.io/thinkphp-apidoc/course/createTpAndInstall)

这个网址我访问不了，一直提示证书不安全，有别的连接地址吗？

**Comment by HGthecode** [comment]
这是github pages 的文档地址，你不能访问文档吗？这里还有gitee的文档地址 https://hg-code.gitee.io/thinkphp-apidoc/course/createTpAndInstall/

**Comment by ScientistPun** [comment]
> 这是github pages 的文档地址，你不能访问文档吗？这里还有gitee的文档地址 https://hg-code.gitee.io/thinkphp-apidoc/course/createTpAndInstall/

看到了，谢谢

**Comment by ScientistPun** [comment]
> > 这是github pages 的文档地址，你不能访问文档吗？这里还有gitee的文档地址 https://hg-code.gitee.io/thinkphp-apidoc/course/createTpAndInstall/
> 
> 看到了，谢谢。可以兼容tp6的注解路由吗？

在使用了官方的注解路由带参数时，如`user/:id`如何编写能够在apidoc上编辑参数呢？

**Comment by HGthecode** [comment]
@ScientistPun 最新版本已支持路由表达式的参数编辑，请下载最新的前端文件替换。并在接口注解中加入 `@Apidoc\ParamType("route")` 来指定参数模式。可参考[演示站点](https://apidoc.demo.hg-code.com/apidoc/?appKey=admin)，的基础示例控制器下的 路由带参接口，[示例代码在这](https://github.com/HGthecode/thinkphp-apidoc-demo/blob/multiApp/app/admin/controller/BaseDemo.php)

**Comment by ScientistPun** [comment]
@HGthecode 我也看到了文档上说支持直接写`@Route("/xxx")`这种方法，但`Route("/xxx:param")`这种支持吗？

**Comment by HGthecode** [comment]
@ScientistPun 不清楚你是怎么使用的，我通过以下注释测试是正常的
```php
   /**
     * @Apidoc\title("注解路由带参")
     * @Route("baseDemo/routeTest/:name/<age>", method="GET")
     * @Apidoc\ParamType("route")
     * @Apidoc\param("name",type="string",desc="姓名" )
     * @Apidoc\param("age",type="string",desc="年龄" )
     * @Apidoc\Returned("data", type="array", desc="入参")
     */
    public function routeTest($name,$age){
        return show(0,"",['name'=>$name,'age'=>$age]);
    }
```
如果还有问题，你可以加我q：376401263把你详细的使用方式告诉我，帮你分析具体原因
