### ISSUE TITLE
本地composer安装好 输入/apidoc访问报错

### ISSUE THREAD

**Issue by htdage** [HGthecode/thinkphp-apidoc#60]
![image](https://user-images.githubusercontent.com/41135954/195492245-721e4a09-a6fa-4d36-adcb-7acdbb406670.png)

**Comment by HGthecode** [comment]
看报错信息像是请求的地址与你的项目地址不一致，请检查前端配置文件`/apidoc/config.js`中的HTTP.HOSTS配置是否配置正确，可参考文档[https://hg-code.gitee.io/thinkphp-apidoc/config/page/#http-hosts](https://hg-code.gitee.io/thinkphp-apidoc/config/page/#http-hosts)如果是当前站点，可清空HOSTS配置

**Comment by htdage** [comment]
> 看报错信息像是请求的地址与你的项目地址不一致，请检查前端配置文件`/apidoc/config.js`中的HTTP.HOSTS配置是否配置正确，可参考文档https://hg-code.gitee.io/thinkphp-apidoc/config/page/#http-hosts如果是当前站点，可清空HOSTS配置

关闭了hosts还是会访问这个连接 很奇怪
![image](https://user-images.githubusercontent.com/41135954/195493672-f6fa1ffe-6946-48b2-be30-46fc1f26ca5f.png)

![image](https://user-images.githubusercontent.com/41135954/195493651-9984fc0f-c161-47b4-a31c-60d7ca5c92ce.png)

**Comment by htdage** [comment]
1

**Comment by HGthecode** [comment]
修改前端配置后，清除一下浏览器缓存尝试一下

**Comment by htdage** [comment]
可以了 谢谢

**Comment by HGthecode** [comment]
不客气哈
