### ISSUE TITLE
请问下 响应结果里面的code message 如何编辑

### ISSUE THREAD

**Issue by htdage** [HGthecode/thinkphp-apidoc#62]
这两个我想自定义 在文档中没找到有说明如何修改

![image](https://user-images.githubusercontent.com/41135954/195528740-bf8b4106-329a-4036-9e6f-9170053322b9.png)

**Comment by HGthecode** [comment]
请参考文档[https://hg-code.gitee.io/thinkphp-apidoc/config/#responses](https://hg-code.gitee.io/thinkphp-apidoc/config/#responses)
