### ISSUE TITLE
1.1.1版本漏了全部分组

### ISSUE THREAD

**Issue by ken678** [HGthecode/thinkphp-apidoc#7]
左侧分组显示不正常，漏写全部

**Comment by HGthecode** [comment]
v1.x版本的控制器分组，没有“全部”的选项，不选则为全部。选择分组后，选择框右侧会有一个×的按钮，点击即可清空选项

**Comment by ken678** [comment]
我前端是这样显示的
https://img.imgdb.cn/item/60306621e7e43a13c6ce3770.jpg

**Comment by HGthecode** [comment]
请升级v1.1.2已解决
