### ISSUE TITLE
markdown文档配置docs不支持{:version}么？配置了好像不生效

### ISSUE THREAD

**Issue by xiazhicong** [HGthecode/thinkphp-apidoc#9]
markdown文档配置docs不支持{:version}么？配置了好像不生效

**Comment by HGthecode** [comment]
v2.1.0之后的版本，由于将`versions`改为用`apps`配置，所以docs的配置可以参考我演示项目的配置：
```php
// md文档
    'docs'              => [
        'menu_title' => '开发文档',
        'menus'      => [
            ['title'=>'md语法示例','path'=>'docs/Use'],
            [
                'title'=>'HTTP响应编码',
                'items'=>[
                    ['title'=>'status错误码说明','path'=>'docs/HttpStatus'],
                    ['title'=>'code错误码说明','path'=>'docs/HttpCode_${app[0].folder}_${app[1].folder}'],
                ],
            ]
        ]
    ],
```
变量写法${app[N].folder}其中的N表示apps中配置的层级，可参考[可用变量说明](https://hg-code.gitee.io/thinkphp-apidoc/config/#path%E3%80%81template%E5%8F%AF%E7%94%A8%E5%8F%98%E9%87%8F%E8%AF%B4%E6%98%8E)

**Comment by xiazhicong** [comment]
你得演示项目在哪里下载呢？https://apidoc.demo.hg-code.com/apidoc/

**Comment by xiazhicong** [comment]
> 你得演示项目在哪里下载呢？https://apidoc.demo.hg-code.com/apidoc/

我已经看到了，谢谢

**Comment by HGthecode** [comment]
不客气，欢迎star😄
